import fs from "node:fs";
import path from "node:path";
import { describe, expect, it } from "vitest";

/**
 * Every hand-written `fuji-*` class a component puts on an element must have
 * a matching selector in the shipped stylesheets. These classes are not
 * generated by Tailwind's scanner - they are authored by hand in base.css -
 * so nothing fails when one goes missing: the component renders, the class
 * attribute is "correct", and the styling is silently absent.
 *
 * That happened. A range-replace in base.css swallowed the neighbouring
 * `.fuji-carousel` block, every stepped carousel lost its `--fuji-cv-per`,
 * and the only symptom was slides at the wrong width in a Storybook page.
 */
const styles = ["tokens.css", "fuji-theme.css", "base.css"]
  .map((file) => fs.readFileSync(path.join(__dirname, file), "utf8"))
  .join("\n");

function walk(dir: string, out: string[] = []): string[] {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) walk(full, out);
    else if (/\.tsx?$/.test(entry.name) && !/\.test\./.test(entry.name)) out.push(full);
  }
  return out;
}

const COMPONENTS = path.join(__dirname, "..", "components");
const referenced = new Set<string>();
for (const file of walk(COMPONENTS)) {
  const source = fs.readFileSync(file, "utf8");
  // Class tokens only: `fuji-foo` inside a string, not `--fuji-foo` tokens or
  // `data-fuji-foo` attributes.
  for (const [, name] of source.matchAll(/(?<![-\w])(fuji-[a-z0-9-]+)(?![\w-])/g)) {
    if (/^fuji-(theme|radius|elevation)$/.test(name)) continue;
    // `[fuji-ui]` console prefixes, and template prefixes like
    // `fuji-toast-icon-${variant}` (their expansions are checked by the
    // component's own tests).
    if (name === "fuji-ui" || name.endsWith("-")) continue;
    referenced.add(name);
  }
}

describe("hand-written fuji-* classes", () => {
  it("are all defined as selectors in the shipped stylesheets", () => {
    // A class selector, or a keyframe name (`animation: fuji-spin ...` is
    // referenced by name, not by class).
    const defined = (name: string) =>
      new RegExp(`\\.${name}(?![\\w-])`).test(styles) ||
      new RegExp(`@keyframes ${name}(?![\\w-])`).test(styles);
    // Marker classes: hooks for scripts/tests, deliberately unstyled.
    const MARKERS = new Set(["fuji-digit-static"]);
    const missing = [...referenced].filter((name) => !MARKERS.has(name) && !defined(name));
    expect(missing).toEqual([]);
  });

  it("sees a representative set (so the assertion above is not vacuous)", () => {
    for (const name of [
      "fuji-raised",
      "fuji-carousel",
      "fuji-motion-modal",
      "fuji-digit",
      "fuji-ripple-wave",
    ]) {
      expect(referenced.has(name)).toBe(true);
    }
  });
});
