import { useState } from "react";
import { FujiProvider, Button, Input, Card, Dialog } from "@fujiui/react";
import type { FujiTheme, FujiElevation } from "@fujiui/react";

export default function App() {
  const [theme, setTheme] = useState<FujiTheme>("light");
  const [elevation, setElevation] = useState<FujiElevation>("regular");

  return (
    <FujiProvider theme={theme} elevation={elevation}>
      <div className="p-6 flex flex-col gap-4">
        <h1 className="text-2xl font-bold">Fixture: Tailwind consumer with preflight</h1>
        <p className="text-sm text-gray-600">
          This app runs its own Tailwind v4 build (preflight included) alongside{" "}
          <code>@fujiui/react/styles.css</code>. The plain <code>flex</code>/<code>p-4</code>/
          <code>gap-4</code> classes below are generated by THIS app's own Tailwind, unprefixed - they should
          render normally and never touch Fuji's internals.
        </p>

        <div className="flex gap-2">
          {(["light", "dark", "glass"] as const).map((t) => (
            <button
              key={t}
              type="button"
              onClick={() => setTheme(t)}
              className="rounded border border-gray-400 px-3 py-1"
              data-testid={`theme-${t}`}
            >
              {t} {theme === t ? "(active)" : ""}
            </button>
          ))}
          <button
            type="button"
            onClick={() => setElevation(elevation === "regular" ? "floating" : "regular")}
            className="rounded border border-gray-400 px-3 py-1"
            data-testid="elevation-toggle"
          >
            elevation: {elevation}
          </button>
        </div>

        <Card className="p-4 flex flex-col gap-3 max-w-md">
          <div className="flex gap-2">
            <Button tone="default">Default</Button>
            <Button tone="fire">Fire</Button>
            <Button tone="water">Water</Button>
            <Button tone="forest">Forest</Button>
            <Button tone="sun">Sun</Button>
          </div>
          <Button size="lg" data-testid="lg-button">
            Large button (checking horizontal padding)
          </Button>
          <Input placeholder="Type here to check focus ring" data-testid="fuji-input" />
          <Dialog>
            <Dialog.Trigger render={<Button data-testid="dialog-trigger">Open dialog</Button>} />
            <Dialog.Content data-testid="dialog-content">
              <Dialog.Title>Portal content</Dialog.Title>
              <p>
                Rendered in a portal, outside both the provider subtree and this app's own Tailwind scan
                roots.
              </p>
              <Input placeholder="Focus me inside the dialog" />
            </Dialog.Content>
          </Dialog>
        </Card>

        <div
          className="border-2 border-gray-800 p-4 flex flex-col gap-2 rounded-lg"
          data-testid="host-tailwind-box"
        >
          <h2 className="text-lg font-semibold">
            Host's own Tailwind layout (unprefixed, real Tailwind classes)
          </h2>
          <p className="text-sm">
            This box, its border, padding, flex layout, and rounded corners are all plain Tailwind utilities
            from THIS app's own build - proving Fuji's <code>fj:</code>-prefixed CSS never overrides them, and
            vice versa.
          </p>
        </div>

        {/* A native, unstyled button - if Fuji's preflight-free stylesheet were somehow leaking, or if THIS app's
            preflight somehow broke Fuji's own control resets, this would look identical to (or bizarrely different
            from) both Fuji's Button and a default OS button. It should render as this app's preflight-reset plain
            button (no OS chrome), completely independent of Fuji. */}
        <button type="button" data-testid="host-plain-button">
          Host's own plain unstyled &lt;button&gt; (preflight-reset baseline)
        </button>
      </div>
    </FujiProvider>
  );
}
